services:
  openvidu:
    image: openvidu/openvidu-dev:2.28.0
    ports:
      - 4443:4443
    networks:
      - openvidu-call-polls-network
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
    restart: on-failure

  openvidu-call-polls-back:
    build:
      context: openvidu-call-back-java
      dockerfile: openvidu-call-polls-back-java.Dockerfile
    restart: on-failure
    networks:
      - openvidu-call-polls-network
    environment:
      - SERVER_PORT=5442
      - OPENVIDU_URL=http://openvidu:4443
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
    ports:
      - 5442:5442
    depends_on:
      - openvidu
  
  openvidu-call-polls-front:
    build:
      context: openvidu-call-front
      dockerfile: openvidu-call-polls-front.Dockerfile
    ports:
      - 4200:4200
    restart: on-failure
    networks:
      - openvidu-call-polls-network
    depends_on:
      - openvidu-call-polls-back


networks:
  openvidu-call-polls-network:
    driver: bridge
