services:
  openvidu:
    image: openvidu/openvidu-dev:2.28.0
    ports:
      - ${OPENVIDU_PORT:-4443}:${OPENVIDU_PORT:-4443}
    networks:
      - openvidu-call-polls-network
    environment:
      - HTTPS_PORT=${OPENVIDU_PORT:-4443}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
    restart: on-failure

  openvidu-call-polls:
    depends_on:
      - openvidu
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - ${SERVER_PORT:-5000}:${SERVER_PORT:-5000}
    networks:
      - openvidu-call-polls-network
    environment:
      - SERVER_PORT=${SERVER_PORT:-5000}
      - OPENVIDU_URL=${OPENVIDU_URL:-http://openvidu:4443}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
      - CALL_PRIVATE_ACCESS=${CALL_PRIVATE_ACCESS:-ENABLED}
      - CALL_USER=${CALL_USER:-admin}
      - CALL_SECRET=${CALL_SECRET:-MY_SECRET}
      - CALL_ADMIN_SECRET=${CALL_ADMIN_SECRET:-MY_SECRET}
      - CALL_RECORDING=${CALL_RECORDING:-ENABLED}
      - CALL_BROADCAST=${CALL_BROADCAST:-ENABLED}
      - OPENVIDU_CALL_POLLS_SYNC=${OPENVIDU_CALL_POLLS_SYNC:-ENABLED}
    restart: on-failure


networks:
  openvidu-call-polls-network:
    driver: bridge