services:
  openvidu:
    image: openvidu/openvidu-dev:2.28.0
    ports:
      - ${OPENVIDU_PORT:-4443}:${OPENVIDU_PORT:-4443}
    networks:
      - openvidu-call-polls-network
    environment:
      - HTTPS_PORT=${OPENVIDU_PORT:-4443}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
    restart: on-failure

  openvidu-call-polls:
    depends_on:
      - openvidu
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - ${SERVER_PORT:-5000}:${SERVER_PORT:-5000}
    networks:
      - openvidu-call-polls-network
    environment:
      - SERVER_PORT=${SERVER_PORT:-5000}
      - OPENVIDU_URL=${OPENVIDU_URL:-http://openvidu:4443}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
    restart: on-failure


networks:
  openvidu-call-polls-network:
    driver: bridge